#!/bin/bash
set -e

# Configurable variables.
LINUX_DEV_PATH=${LINUX_DEV_PATH:-$HOME/linux}

# $@: message to display.
function fatal()
{
	echo buildLinux: $@ >&2
	exit 1
}

# Sanity checks.
[ ! -d $LINUX_DEV_PATH ] && fatal "can't find linux dev path at $LINUX_DEV_PATH"
[ ! -f $LINUX_DEV_PATH/REPORTING-BUGS ] && \
	fatal "Doesn't look like a linux dev path: $LINUX_DEV_PATH"
[ $EUID = 0 ] && fatal "Don't run as root, causes file ownership pain"

# Ref: http://stackoverflow.com/a/6481016
cores=$(grep -c ^processor /proc/cpuinfo)

pushd $LINUX_DEV_PATH >/dev/null

echo Configuring kernel...

if [ ! -z "$REBUILD" ] || [ ! -f .config ]; then
	make mrproper >/dev/null
	make defconfig >/dev/null
fi

configLinux
# Set any new options implied by configLinux to default.
mak olddefconfig

echo Compiling kernel...
# 1 extra thread to account for I/O waiting.
make -j$((cores + 1)) >/dev/null

if [ -z "$DONT_INSTALL" ]; then
	echo Installing kernel...
	NO_DONE=y installLinux
fi

popd >/dev/null

[ -z "$NO_DONE" ] && echo Done!
