#!/bin/bash
set -e; set -o pipefail

source shared_kernel_functions.sh

# Configurable variables.
LINUX_DEV_PATH=${LINUX_DEV_PATH:-$HOME/linux}

push_linux

gdb vmlinux --ex "target remote localhost:1234"

pop
