#!/bin/bash
set -e; set -o pipefail

# Configurable variables.
LINUX_DEV_PATH=${LINUX_DEV_PATH:-$HOME/linux}

pushd $LINUX_DEV_PATH >/dev/null

gdb vmlinux --ex "target remote localhost:1234"

popd >/dev/null
