#!/bin/bash
set -e; set -o pipefail

source shared_kernel_functions.sh

# Configurable variables.
KERNDEV_PATH=${KERNDEV_PATH:-$HOME/kerndev}
LINUX_DEV_PATH=${LINUX_DEV_PATH:-$HOME/linux}

ROOTFS_IMAGE_PATH=$KERNDEV_PATH/rootfs.img
INITRD_IMAGE_PATH=$KERNDEV_PATH/init.img
KERNEL_IMAGE_PATH=$LINUX_DEV_PATH/arch/x86/boot/bzImage

# Functions.

function mak()
{
	make $make_opts $@
}


# Sanity checks.
if [ ! -f $ROOTFS_IMAGE_PATH ]; then
   echo "installLinux: can't find root fs image at $ROOTFS_IMAGE_PATH" >&2
   exit 1
fi
if [ ! -f $KERNEL_IMAGE_PATH ]; then
    echo "installLinux: can't find kernel image at $KERNEL_IMAGE_PATH" >&2
    exit 1
fi
if [ ! -f $LINUX_DEV_PATH/REPORTING-BUGS ]; then
    echo "installLinux: doesn't look like a linux dev path: $LINUX_DEV_PATH" >&2
    exit 1
fi


elevate $@

push_linux

echo Mounting rootfs image...
umount /mnt &>/dev/null || true
mount -o loop $ROOTFS_IMAGE_PATH /mnt
trap "umount /mnt" EXIT

echo Installing headers and modules...
mak headers_install INSTALL_HDR_PATH=/mnt/usr/ >/dev/null
mak modules_install INSTALL_MOD_PATH=/mnt/ >/dev/null

echo Installing initrd image...
mkinitcpio -r /mnt -k $KERNEL_IMAGE_PATH -g $INITRD_IMAGE_PATH &>/dev/null

pop

if [ -z "$NO_DONE" ]; then
    echo Done!
fi
