#!/bin/bash

# TODO: Get maintainer for all files in dir if no args?
if [[ -z "$1" ]]; then
	echo usage: get_maintainer [[files...]] >&2
	exit 1
fi

# Hacky way of determining we're not in the kernel root.
isntroot() {
	[[ ! -f REPORTING-BUGS ]]
}

gotoroot() {
	while isntroot; do
		cd ..

		if [[ $PWD = "/" ]]; then
			echo get_maintainer: couldn\'t find linux root >&2
			exit 1
		fi
	done
}

for file in $@; do
	path=$(readlink -f $file)
	if [[ ! -f $path ]]; then
		echo get_maintainer: no such file: $path >&2
		exit 1
	fi

	pushd $(dirname $path) > /dev/null

	gotoroot
	echo -e "$file\n"
	scripts/get_maintainer.pl --subsystem -f $path

	popd > /dev/null
done
