#!/bin/bash
set -e; set -o pipefail; source kerndev-shared.sh

output_format="%-15s\t%s\n"

# Functions.

# Enter $1, stash if necessary, and store previous reference in $prevref.
function enterdir()
{
	push $1

	prevref=$(git rev-parse --abbrev-ref=strict HEAD)
	# If this is 'HEAD', we can't find a matching branch so just use the
	# commit hash instead.
	[ "$prevref" == "HEAD" ] && prevref=$(git rev-parse HEAD)

	changed=$(git status --porcelain)
	if [ ! -z "$changed" ]; then
		git stash -q --include-untracked
		stashed=y
	fi
}

# Resore $prevref, if stashed changes, pop them.
function exitdir()
{
	git checkout -q $prevref

	if [ ! -z "$stashed" ]; then
		git stash pop -q
		unset stashed
	fi

	pop
}

# Update kernel tree.
#
# $1:    Directory of kernel tree.
# $2...: Branches to update.
function update()
{
	dir=$1
	shift

	enterdir $dir

	for branch in $@; do
		git checkout -q $branch
		git pull -q --rebase

		printf $output_format $branch $PWD
	done

	exitdir
}

echo Updating linux git trees...

printf $output_format "BRANCH" "DIR"

# Your trees may vary :-)
update ~/linux              master linux-stable linux-next
update ~/linux-stable-queue master
update ~/linux-staging      master test staging-next staging-testing
update ~/linux-mm           master
update ~/linux-aarch64      master devel fixes/core

say_done
