#!/bin/bash
set -e; set -o pipefail; source kerndev-shared.sh

push_linux

if [[ -n "$REBUILD" ]] || [[ ! -f .config ]]; then
	mak mrproper
	mak defconfig
fi

# Show extra version info.
kenable local_version_auto

# Required for systemd.
kenable fhandle

# We like devtmpfs.
kenable devtmpfs

# Disable unneeded wifi interface which spawns spurious debug output.
kdisable cfg80211

# tun/tap.
kenable tun

# virtio stuff.
kenable virtio_pci virtio_mmio virtio_blk virtio_net virtio_console \
	virtio_pci_legacy virtio_input virtio_mmio_cmdline_devices
kdisable hw_random_virtio virtio_balloon

# Debugging settings.
kenable debug_info debug_info_split debug_info_dwarf4 gdb_scripts frame_pointer
kdisable debug_info_reduced debug_rodata

# Gain access to /proc/config.gz.
kenable ikconfig ikconfig_proc

# Avoid legacy hotplug.
# Taken with thanks from http://unix.stackexchange.com/a/116888.
scripts/config --set-str uevent_helper_path ""

# Optionally enable flags for docker support.
[[ -n "$ENABLE_DOCKER_SUPPORT" ]] && \
    kenable netfilter_advanced dm_thin_provisioning bridge bridge_netfilter \
	    devpts_multiple_instances cgroup_device memcg macvlan veth \
	    nf_nat_ipv4 nf_nat netfilter_xt_match_{conntrack,addrtype} \
	    blk_cgroup blk_dev_throttling cgroup_perf cgroup_hugetlb \
	    net_cls_cgroup cfs_bandwidth rt_group_sched netprio_cgroup \
	    cgroup_net_prio btrfs_fs

# Optionally, we are interested in code coverage.
[[ -n "$ENABLE_GCOV" ]] && \
	kenable debug_fs gcov_kernel gcov_format_autodetect gcov_profile_all

pop
