#!/bin/bash
set -e; set -o pipefail; source kerndev-shared.sh

# Functions.

# Configure kernel setting to $1 for settings in $@...
function config()
{
	choice=$1
	shift

	for setting in $@; do
		scripts/config --$choice $setting
	done
}

# Enable kernal settings $@...
function kenable()
{
	config enable $@
}

# Disable kernal settings $@...
function kdisable()
{
	config disable $@
}

push_linux

# Show extra version info.
kenable local_version_auto

# Required for systemd.
kenable fhandle

# Disable unneeded wifi interface which spawns spurious debug output.
kdisable cfg80211

# tun/tap.
kenable tun

# virtio stuff.
kenable virtio_pci virtio_mmio virtio_blk virtio_net virtio_console \
	virtio_pci_legacy virtio_input virtio_mmio_cmdline_devices
kdisable hw_random_virtio virtio_balloon

# Debugging settings.
kenable

kenable debug_info debug_info_split debug_info_dwarf4 gdb_scripts \
	frame_pointer debug_info_reduced debug_rodata

# Gain access to /proc/config.gz.
kenable ikconfig ikconfig_proc

# Optionally, we are interested in code coverage.
if [ ! -z "$ENABLE_GCOV" ]; then
	kenable debug_fs gcov_kernel gcov_format_autodetect gcov_profile_all
fi

pop
