#!/bin/bash
set -e; set -o pipefail; source kerndev-shared.sh

# Default to all .c and .h files in the directory.
args=${@:-*.[ch]}
# Check file (not patch), quiet (unless error), show error types and don't
# bother with a per-file summary.
check_opts="-f -q --show-types --no-summary"

$LINUX_DEV_PATH/scripts/checkpatch.pl $check_opts $args
