#!/bin/bash
set -e; set -o pipefail

source shared_kernel_functions.sh

# Functions.

function enterdir() {
	cd $1

	prevbranch=$(git rev-parse --abbrev-ref HEAD)

	changed=$(git status --porcelain)
	if [ ! -z "$changed" ]; then
		git stash -q --include-untracked
		stashed=y
	fi
}

function exitdir() {
	git checkout -q $prevbranch

	if [ ! -z "$stashed" ]; then
		git stash pop -q
		unset stashed
	fi
}

function update() {
	git checkout -q $1
	git pull -q --rebase

	printf "%20s\t$PWD\n" $1
}

pushd ~ >/dev/null

echo Updating linux git trees...

# ~~~

enterdir ~/linux

update master
update linux-stable
update linux-next

exitdir

# ~~~

enterdir ~/linux-stable-queue

update master

exitdir

# ~~~

enterdir ~/linux-staging

update master
update test
update staging-next
update staging-testing

exitdir

# ~~~

enterdir ~/linux-mm

update master

exitdir

# ~~~

enterdir ~/linux-aarch64

update master
update devel
update fixes/core

exitdir

popd >/dev/null

[ -z "$NO_DONE" ] && echo Done! || true
